### ISSUE TITLE
Inventories have been lost in host transfer

### ISSUE THREAD

**Issue by cbullers** [cbullers/valiance-bug-tracker#1]
All player inventories (all items players held) before the transfer have been lost.
Suggested to download old map before old host expires and attempt transfers. If not, a manual transfer may be in order.

ETR (Estimated Time to Restoration): Unknown

**Comment by Noobley324** [comment]
Bogi has been giving players the items they remember having. There's nothing that can be done to get your entire inventory back.

**Comment by cbullers** [comment]
Appears most inventories have been recovered from Bogi

-locked
